language: java
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
   hosts:
       - travis
   hostname: travis

script: mvn clean test
